### ISSUE TITLE
the progressbar can't display in pycharm

### ISSUE THREAD

**Issue by lzhang6** [rasbt/pyprind#35]
When I use terminal to run the code, the progress bar is ok
while using pycharm, the progressbar can't show in result.

**Comment by rasbt** [comment]
Hm, maybe PyCharm doesn't show the standard error output? By default, pyprind's objects are using `stream=2` to output results to stderr (users suggested this so they can pip the "real" output by their program to other files and such. 

If you set `stream=1` (which is stdout), does it work?

```python
bar = pyprind.ProgBar(n, stream=1)
for i in range(n):
    time.sleep(timesleep) # your computation here
    bar.update()
```

**Comment by lzhang6** [comment]
Hi

after setting stream to 1,It still can't work

Sincerely

Liang

**Comment by rasbt** [comment]
Ah, you are right, for some reason, it doesn't work with `stream=1` here. However, I just gave it a try setting the stream manually and it works like a charm(m) ;)

```python
import pyprind
import sys
import time

n = 100
bar = pyprind.ProgBar(n), stream=sys.stdout)
for i in range(n):
    time.sleep(0.1)
    bar.update()
```    
    
![screen shot 2016-09-06 at 10 36 09 pm](https://cloud.githubusercontent.com/assets/5618407/18297923/92de4a60-7482-11e6-9f85-6bc25a10511e.png)

Let me know if this works for you as well, and I'd be happy to add a note to the README/docs if this solves the problem.

**Comment by lzhang6** [comment]
it works for me， thanks a lot.
You should add an example using while loop. 
tqdm doesn't support while loop

**Comment by rasbt** [comment]
glad to heart that this solution works and adding a while-loop example is a good idea, thanks for the suggestion (just added one). Btw. do you know if tqdm work with PyCharm out of the box? Never tried this package, looks like an interesting alternative though

**Comment by lzhang6** [comment]
tqdm can display in pycharm.

but it didn't support tqdm.

**Comment by rasbt** [comment]
Ah, I just remembered that I added an `sys.stdout.isatty()` check for setting the stream, which evaluates to `False` in PyCharm. Just made a little modification and it should work with PyCharm out of the box. If you like, you can upgrade to 2.9.9 via

`pip install pyprind --upgrade`

**Comment by dE1l** [comment]
it's not working for pyprind 2.11.0 and pycharm 2016.3.3.

i'm doing this https://github.com/rasbt/pyprind/issues/35#issuecomment-245158319
![2017-05-04_12-27-30](https://cloud.githubusercontent.com/assets/8767620/25697909/79879378-30c5-11e7-846a-2ce0b4c449a9.png)

**Comment by rasbt** [comment]
Hi,
hm that's weird, just tested in on PyCharm with and without sys.stdout as stream and it seems to work fine in both cases. Can you maybe check via `print(pyprind.__version__)` that this is indeed pyprind 2.11? Another explanation would be that there might have been some weirdness in PyCharm 2016 regarding standard outputs? ( was running this on the latest version, 2017.1.2)

<img width="1110" alt="screen shot 2017-05-04 at 11 18 45 am" src="https://cloud.githubusercontent.com/assets/5618407/25711035/f8f99bc4-30bb-11e7-968f-2d9e9dd76391.png">

<img width="1106" alt="screen shot 2017-05-04 at 11 18 31 am" src="https://cloud.githubusercontent.com/assets/5618407/25711037/f9196b34-30bb-11e7-9c3d-7b5b96906fd8.png">

**Comment by umniq** [comment]
The behavior depends on PyCharm's option "Show command line afterwards". If it is on, PyCharm invokes IPython console, you will see each update on the separate line. If it is off, the behavior as expected.

**Comment by rasbt** [comment]
Thanks for the note. So it seems that it's not a bug after all !? :)

**Comment by umniq** [comment]
It's PyCharm's [issue]( https://github.com/tqdm/tqdm/issues/307)
