### ISSUE TITLE
Debian packaging in progress

### ISSUE THREAD

**Issue by anarcat** [rasbt/pyprind#42]
Hi!

This is a friendly notice to let you know that [Debian](https://debian.org/) is working on packaging your software for Debian. You can follow the progress of that work in [bug #867800](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867800) in the Debian Bug Tracking System (BTS).

The source code for the Debian package is in [this git repository](https://anonscm.debian.org/cgit/python-modules/packages/pyprind.git/). It will be uploaded into Debian shortly, at which point it will end up in the [NEW queue](https://ftp-master.debian.org/new.html) for legal review. Once the NEW process is completed, it takes about 10 days for the package to trickle down into "testing", which will become the next Debian release. This means your software will eventually be shipped in a "long term support" release, which last from three to five years, according to the [current statistics](https://wiki.debian.org/DebianReleases#Production_Releases).

If you are interested in maintaining the package yourself upstream, that is definitely possible. You can either upload the package yourself if you are a Debian member or I can act as a sponsor when a new release is published.

This is just a notification, but can also act as a coordination point for upstream packaging if you wish to followup on this. otherwise, feel free to close this issue whenever you like.

**Comment by rasbt** [comment]
Thanks for the note! I am really happy to hear that the package turns out to be useful to you and that you are are planning to include in the upcoming Debian release. I will close this issue for now, but please let me know in case any questions should arise.

**Comment by anarcat** [comment]
No problem - everything looks fine for now. The package went through the NEW review without a hitch and is now in "unstable". You can subscribe to package changes by email in the [package tracker](https://tracker.debian.org/pkg/pyprind) if you're interested. The [repology page](https://repology.org/metapackage/pyprind/versions) also shows its versions, although it needs to be merged with the [already existing page](https://repology.org/metapackage/python:pyprind/versions) for other distros.
